In [57]:
#numpy is designed for fast numerical computing,it is a package for scientific computing with python
import numpy as np

In [ ]:
#create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#create numpy from scratch
import numpy as np
arr1 = np.zeros((2,3)) #prefill
print(arr1)

arr2 = np.full((2, 3), 100) #prefill with val
print(arr2)

arr3 = np.arange(1, 10) 
print(arr3)



[[0. 0. 0.]
 [0. 0. 0.]]
[[100 100 100]
 [100 100 100]]
[1 2 3 4 5 6 7 8 9]


In [8]:
#mathematical fnx
#aggregation
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))


15
120
1
5
0
4
3.0
1.4142135623730951
3.0


In [10]:
#power fnx

arr = np.array([1, 2, 3, 4, 5])
print(np.square(arr))
print(np.sqrt(arr))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [11]:
#log
arr = np.array([1, 2, 3, 4, 5])
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))



[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [15]:
#rounding
print(np.round(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

print(np.unique(3.14))

print(np.abs(3.14))

3.0
3.0
3.0
[3.14]
3.14
